version: '3'
services:
  react-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
      - ".:/my-app"
      - "/my-app/node_modules"
    environment:
      - CHOKIDAR_USERPOLLING=true
